sudo: required
language: objective-c
osx_image: xcode10.2
rvm:
    - 2.6.3
branches:
    only:
        - master
cache:
    timeout: 86400 # 1 day
    directories:
        - /Users/travis/cache/
        - /Users/travis/.rvm/
before_install:
    - chmod +x ./Scripts/build_docs.sh
    - chmod +x ./Scripts/build_package.sh
    - chmod +x ./Scripts/install_pandoc.sh
install:
    - bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/unity-ci-tools/master/bin/install.sh)
script:
    - bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/unity-ci-tools/master/bin/auth.sh)
    - bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/unity-ci-tools/master/bin/test.sh)
    - bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/unity-ci-tools/master/bin/deauth.sh)
after_success:
    - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then make build; fi
deploy:
    provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: candycoded
    local-dir: build
    upload-dir: build
    skip_cleanup: true
    on:
        branch: master
