language: objective-c
osx_image: xcode9.2
rvm:
- 2.5.0
before_install:
- chmod +x ./Scripts/install.sh
- chmod +x ./Scripts/test.sh
install:
- make install
script:
- make test
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $ACCESS_KEY
  bucket: candycoded
  local-dir: build
  upload-dir: build
  skip_cleanup: true
