sudo: required
language: objective-c
osx_image: xcode10.3
rvm:
  - 2.6.4
branches:
  only:
    - master
cache:
  timeout: 86400 # 1 day
  directories:
    - $HOME/cache/
    - $HOME/.rvm/
install:
  - bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/unity-ci-tools/master/bin/install.sh)
script:
  - bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/unity-ci-tools/master/bin/auth.sh)
  - bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/unity-ci-tools/master/bin/test.sh)
  - bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/unity-ci-tools/master/bin/deauth.sh)
