sudo: required
language: objective-c
osx_image: xcode10.3
rvm:
  - 2.6.3
branches:
  only:
    - master
cache:
  timeout: 86400 # 1 day
  directories:
    - $HOME/cache/
    - $HOME/.rvm/
    - $HOME/Library/Caches/Homebrew
before_cache:
  - brew cleanup
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install shellcheck; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then make install; fi
install:
  - bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/unity-ci-tools/master/bin/install.sh)
script:
  - bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/unity-ci-tools/master/bin/auth.sh)
  - bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/unity-ci-tools/master/bin/test.sh)
  - bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/unity-ci-tools/master/bin/deauth.sh)
  - shellcheck Scripts/*.sh
after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then make build; fi
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: candycoded
  local-dir: build
  upload-dir: build
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
