language: objective-c
osx_image: xcode9.2
rvm:
- 2.5.0
cache:
  directories:
    - ./cache
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/test.sh
install:
- ./Scripts/install.sh
script:
- ./Scripts/test.sh
env:
  global:
  - UNITYCI_PROJECT_NAME="CandyCoded"
